package com.ec.deckxel.utilidad;

public class ModeloPedidoSQLite {

    private String COLUMN_NAME_FECHA;
    private String COLUMN_NAME_CODIGO;
    private String COLUMN_NAME_CANTIDAD;
    private String COLUMN_NAME_DESCRIPCION;
    private String COLUMN_NAME_PRECIOUNIT;
    private String COLUMN_NAME_TOTAL;
    private String COLUMN_NAME_PRODUCTO;
    private String COLUMN_NAME_NOMBRE_PRODUCTO;
    
   
    
    public ModeloPedidoSQLite() {
    }

    public ModeloPedidoSQLite(String COLUMN_NAME_FECHA, String COLUMN_NAME_CODIGO, String COLUMN_NAME_CANTIDAD, String COLUMN_NAME_DESCRIPCION, String COLUMN_NAME_PRECIOUNIT, String COLUMN_NAME_TOTAL) {
        this.COLUMN_NAME_FECHA = COLUMN_NAME_FECHA;
        this.COLUMN_NAME_CODIGO = COLUMN_NAME_CODIGO;
        this.COLUMN_NAME_CANTIDAD = COLUMN_NAME_CANTIDAD;
        this.COLUMN_NAME_DESCRIPCION = COLUMN_NAME_DESCRIPCION;
        this.COLUMN_NAME_PRECIOUNIT = COLUMN_NAME_PRECIOUNIT;
        this.COLUMN_NAME_TOTAL = COLUMN_NAME_TOTAL;
    }

    public ModeloPedidoSQLite(String COLUMN_NAME_FECHA, String COLUMN_NAME_CODIGO, String COLUMN_NAME_CANTIDAD, String COLUMN_NAME_DESCRIPCION, String COLUMN_NAME_PRECIOUNIT, String COLUMN_NAME_TOTAL, String COLUMN_NAME_PRODUCTO) {
        this.COLUMN_NAME_FECHA = COLUMN_NAME_FECHA;
        this.COLUMN_NAME_CODIGO = COLUMN_NAME_CODIGO;
        this.COLUMN_NAME_CANTIDAD = COLUMN_NAME_CANTIDAD;
        this.COLUMN_NAME_DESCRIPCION = COLUMN_NAME_DESCRIPCION;
        this.COLUMN_NAME_PRECIOUNIT = COLUMN_NAME_PRECIOUNIT;
        this.COLUMN_NAME_TOTAL = COLUMN_NAME_TOTAL;
        this.COLUMN_NAME_PRODUCTO = COLUMN_NAME_PRODUCTO;
    }

    public ModeloPedidoSQLite(String COLUMN_NAME_FECHA, String COLUMN_NAME_CODIGO, String COLUMN_NAME_CANTIDAD, String COLUMN_NAME_DESCRIPCION, String COLUMN_NAME_PRECIOUNIT, String COLUMN_NAME_TOTAL, String COLUMN_NAME_PRODUCTO, String COLUMN_NAME_NOMBRE_PRODUCTO) {
        this.COLUMN_NAME_FECHA = COLUMN_NAME_FECHA;
        this.COLUMN_NAME_CODIGO = COLUMN_NAME_CODIGO;
        this.COLUMN_NAME_CANTIDAD = COLUMN_NAME_CANTIDAD;
        this.COLUMN_NAME_DESCRIPCION = COLUMN_NAME_DESCRIPCION;
        this.COLUMN_NAME_PRECIOUNIT = COLUMN_NAME_PRECIOUNIT;
        this.COLUMN_NAME_TOTAL = COLUMN_NAME_TOTAL;
        this.COLUMN_NAME_PRODUCTO = COLUMN_NAME_PRODUCTO;
        this.COLUMN_NAME_NOMBRE_PRODUCTO = COLUMN_NAME_NOMBRE_PRODUCTO;
    }

    public String getCOLUMN_NAME_FECHA() {
        return COLUMN_NAME_FECHA;
    }

    public void setCOLUMN_NAME_FECHA(String COLUMN_NAME_FECHA) {
        this.COLUMN_NAME_FECHA = COLUMN_NAME_FECHA;
    }

    public String getCOLUMN_NAME_CODIGO() {
        return COLUMN_NAME_CODIGO;
    }

    public void setCOLUMN_NAME_CODIGO(String COLUMN_NAME_CODIGO) {
        this.COLUMN_NAME_CODIGO = COLUMN_NAME_CODIGO;
    }

    public String getCOLUMN_NAME_CANTIDAD() {
        return COLUMN_NAME_CANTIDAD;
    }

    public void setCOLUMN_NAME_CANTIDAD(String COLUMN_NAME_CANTIDAD) {
        this.COLUMN_NAME_CANTIDAD = COLUMN_NAME_CANTIDAD;
    }

    public String getCOLUMN_NAME_DESCRIPCION() {
        return COLUMN_NAME_DESCRIPCION;
    }

    public void setCOLUMN_NAME_DESCRIPCION(String COLUMN_NAME_DESCRIPCION) {
        this.COLUMN_NAME_DESCRIPCION = COLUMN_NAME_DESCRIPCION;
    }

    public String getCOLUMN_NAME_PRECIOUNIT() {
        return COLUMN_NAME_PRECIOUNIT;
    }

    public void setCOLUMN_NAME_PRECIOUNIT(String COLUMN_NAME_PRECIOUNIT) {
        this.COLUMN_NAME_PRECIOUNIT = COLUMN_NAME_PRECIOUNIT;
    }

    public String getCOLUMN_NAME_TOTAL() {
        return COLUMN_NAME_TOTAL;
    }

    public void setCOLUMN_NAME_TOTAL(String COLUMN_NAME_TOTAL) {
        this.COLUMN_NAME_TOTAL = COLUMN_NAME_TOTAL;
    }

    public String getCOLUMN_NAME_PRODUCTO() {
        return COLUMN_NAME_PRODUCTO;
    }

    public void setCOLUMN_NAME_PRODUCTO(String COLUMN_NAME_PRODUCTO) {
        this.COLUMN_NAME_PRODUCTO = COLUMN_NAME_PRODUCTO;
    }

    public String getCOLUMN_NAME_NOMBRE_PRODUCTO() {
        return COLUMN_NAME_NOMBRE_PRODUCTO;
    }

    public void setCOLUMN_NAME_NOMBRE_PRODUCTO(String COLUMN_NAME_NOMBRE_PRODUCTO) {
        this.COLUMN_NAME_NOMBRE_PRODUCTO = COLUMN_NAME_NOMBRE_PRODUCTO;
    }

    
   
    
  
    
}
